basePath: /
definitions:
  models.LoginReq:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  models.RegisterReq:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for a github.com/kongzyeons/go-bank
  title: API-BANK
  version: "1.0"
paths:
  /api/v1/auth/logout:
    post:
      consumes:
      - application/json
      description: Logout
      operationId: AuthLogout
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Logout
      tags:
      - Auth API
  /api/v1/auth/ping:
    get:
      consumes:
      - application/json
      description: Ping
      operationId: AuthPing
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Ping
      tags:
      - Auth API
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: Login
      operationId: AuthLogin
      parameters:
      - description: request body
        in: body
        name: LoginReq
        required: true
        schema:
          $ref: '#/definitions/models.LoginReq'
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Login
      tags:
      - Auth API
  /api/v1/register:
    post:
      consumes:
      - application/json
      description: Register
      operationId: AuthRegister
      parameters:
      - description: request body
        in: body
        name: RegisterReq
        required: true
        schema:
          $ref: '#/definitions/models.RegisterReq'
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Register
      tags:
      - Auth API
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
