basePath: /
definitions:
  models.AuthLoginReq:
    properties:
      password:
        example: "123456"
        maxLength: 6
        minLength: 6
        type: string
      username:
        example: admin
        maxLength: 100
        type: string
    required:
    - password
    - username
    type: object
  models.AuthRefreshReq:
    properties:
      refToken:
        type: string
    type: object
  models.AuthRegisterReq:
    properties:
      password:
        example: "123456"
        maxLength: 6
        minLength: 6
        type: string
      username:
        example: admin
        maxLength: 100
        type: string
    required:
    - password
    - username
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for a github.com/kongzyeons/go-bank
  title: API-BANK
  version: "1.0"
paths:
  /api/v1/auth/logout:
    post:
      consumes:
      - application/json
      description: Logout
      operationId: AuthLogout
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Logout
      tags:
      - Auth API
  /api/v1/auth/ping:
    get:
      consumes:
      - application/json
      description: Ping
      operationId: AuthPing
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Ping
      tags:
      - Auth API
  /api/v1/auth/refresh:
    post:
      consumes:
      - application/json
      description: Refresh
      operationId: AuthRefresh
      parameters:
      - description: request body
        in: body
        name: AuthRefreshReq
        required: true
        schema:
          $ref: '#/definitions/models.AuthRefreshReq'
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Refresh
      tags:
      - Auth API
  /api/v1/homepage/greeting:
    get:
      consumes:
      - application/json
      description: GetUserGreetings
      operationId: HomePageGetUserGreetings
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: GetUserGreetings
      tags:
      - HomePage API
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: Login
      operationId: AuthLogin
      parameters:
      - description: request body
        in: body
        name: AuthLoginReq
        required: true
        schema:
          $ref: '#/definitions/models.AuthLoginReq'
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Login
      tags:
      - Auth API
  /api/v1/register:
    post:
      consumes:
      - application/json
      description: Register
      operationId: AuthRegister
      parameters:
      - description: request body
        in: body
        name: AuthRegisterReq
        required: true
        schema:
          $ref: '#/definitions/models.AuthRegisterReq'
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Register
      tags:
      - Auth API
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
